name: React CI
on: [push, pull_request]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install modules
        run: yarn install
      - name: Run ESLint
        run: yarn run lint
